name: flutter_step_count
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  device_info_plus: ^9.0.3
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.2
  get_it: ^7.6.4
  intl: ^0.18.1
  pedometer: ^4.0.1
  permission_handler: ^11.0.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
